import { endZeros } from '../puzzles';

export const solution = {
  name: 'End Zeros',
  my: endZeros,
  best: (value: number): number => {
    const s = String(value);
    return s.length - s.replace(/0*$/, '').length;
  },
  // creative: (n: number) => String(n).match(/0*$/)[0].length
  creative: (n: number) => { // generated by GitHub Co-Pilot
    let count = 0;
    let s = String(n);
    for (let i = s.length - 1; i >= 0; i--) {
      if (s[i] === '0') {
        count++;
      } else {
        break;
      }
    }
    return count;
  }

};
